### ISSUE TITLE
Where should I create the configuration file?

### ISSUE THREAD

**Issue by XIYO** [Watfaq/PowerSession-rs#109]
English translation:

First of all, thank you very much for creating a Windows version.

I am currently running my own asciinema-server. I'd like to store my recordings there, but even if I add settings to `~/.config/asciinema/config` as per the existing instructions, it doesn't seem to work. Is there a way to solve this?

I also created `~/.config/powersession/config` but it didn't apply either.

__config__
```sh
[api]
url = https://asciinema.xiyo.dev
```

**Comment by ibigbug** [comment]
hi,

have you tried

```
PowerSession.exe --server <hostname>
```

**Comment by XIYO** [comment]
my version, installed by winget
```
$ powersession.exe -V
PowerSession 0.1.7
```

i tried `--server` option
```
PowerSession.exe --server https://asciinema.xiyo.dev test
error: Found argument '--server' which wasn't expected, or isn't valid in this context

        If you tried to supply `--server` as a value rather than a flag, use `-- --server`

USAGE:
    PowerSession.exe [OPTIONS] <SUBCOMMAND>

For more information try --help
PowerSession.exe test --server https://asciinema.xiyo.dev
```

**Comment by ibigbug** [comment]
right. try upgrading to 0.1.8 ?

**Comment by XIYO** [comment]
> right. try upgrading to 0.1.8 ?

I installed it using `winget`, so I want to update it using winget update. The current latest version of winget is 1.7, can you provide the package in version 1.9?

**Comment by ibigbug** [comment]
winget publish is broken somehow. And I don't have much time looking into it right now.

**Comment by ibigbug** [comment]
the publish is fixed https://github.com/Watfaq/PowerSession-rs/releases/tag/v0.1.11
